blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/your-discord-invite
    about: Join our Discord for real-time chat and support
  - name: 📚 Documentation
    url: https://github.com/99Problemsx/Illusion/wiki
    about: Check the Wiki for guides and documentation
  - name: 💡 Discussions
    url: https://github.com/99Problemsx/Illusion/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/99Problemsx/Illusion/security/advisories/new
    about: Report security vulnerabilities privately
