name: Issue & PR Auto-Assignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
    - name: Auto-assign issue
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        script: |
          // Auto-assign labels based on title/body
          const title = context.payload.issue.title.toLowerCase();
          const body = (context.payload.issue.body || '').toLowerCase();
          const labels = [];
          
          if (title.includes('bug') || body.includes('bug')) labels.push('bug');
          if (title.includes('feature') || title.includes('enhancement')) labels.push('enhancement');
          if (title.includes('docs') || title.includes('documentation')) labels.push('documentation');
          if (body.includes('plugin')) labels.push('plugin');
          if (body.includes('pbs')) labels.push('pbs');
          if (body.includes('graphic') || body.includes('sprite')) labels.push('graphics');
          if (body.includes('performance')) labels.push('performance');
          if (body.includes('security')) labels.push('security');
          
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
          }
          
    - name: Auto-assign PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          // PR labels will be added by labeler action
          console.log('PR created, labels will be auto-assigned');
