name: Discord Notifications

on:
  push:
    branches: [ main ]
  release:
    types: [published]
  issues:
    types: [opened]
  pull_request:
    types: [opened, merged]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Send Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "🎮 Illusion - New Activity"
        description: |
          **Event**: ${{ github.event_name }}
          **Actor**: ${{ github.actor }}
          **Commit**: ${{ github.event.head_commit.message }}
        color: 0x3498db
        username: Illusion Bot
        avatar_url: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/25.png
