name: Enhanced Discord Notifications

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened, ready_for_review]
  release:
    types: [published]

jobs:
  notify-detailed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Issue Opened
      if: github.event_name == 'issues' && github.event.action == 'opened'
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "🐛 New Issue Opened"
        description: |
          **Issue #${{ github.event.issue.number }}**: ${{ github.event.issue.title }}
          
          **Created by**: @${{ github.event.issue.user.login }}
          **Labels**: ${{ join(github.event.issue.labels.*.name, ', ') }}
          
          [View Issue](${{ github.event.issue.html_url }})
        color: 0xffa500
        username: Illusion Issues Bot
        
    - name: PR Opened
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "🔀 New Pull Request"
        description: |
          **PR #${{ github.event.pull_request.number }}**: ${{ github.event.pull_request.title }}
          
          **Author**: @${{ github.event.pull_request.user.login }}
          **Branch**: `${{ github.event.pull_request.head.ref }}` → `${{ github.event.pull_request.base.ref }}`
          **Changes**: +${{ github.event.pull_request.additions }} -${{ github.event.pull_request.deletions }}
          
          [Review PR](${{ github.event.pull_request.html_url }})
        color: 0x0366d6
        username: Illusion PR Bot
        
    - name: Release Published
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "🎉 New Release: ${{ github.event.release.tag_name }}"
        description: |
          **${{ github.event.release.name }}**
          
          ${{ github.event.release.body }}
          
          [Download Release](${{ github.event.release.html_url }})
        color: 0x28a745
        username: Illusion Releases Bot
