name: Release Launcher

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: launcher-electron/package-lock.json
    
    - name: Install dependencies
      working-directory: ./launcher-electron
      run: npm ci
    
    - name: Build and release
      working-directory: ./launcher-electron
      run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          launcher-electron/dist/*.exe
          launcher-electron/dist/*.dmg
          launcher-electron/dist/*.AppImage
          launcher-electron/dist/*.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
